"""Fourier Neural Operator for acoustic wavefield surrogate modelling.

Learns to map (velocity model, source parameters, receiver positions) →
receiver traces, replacing the expensive FDTD solver at inference time.

Architecture
============
The FNO operates in two stages:

1. **Encoder** — A 2-D Fourier Neural Operator processes the velocity
   field (with source/receiver positions encoded as extra channels) and
   produces a latent spatial representation.

2. **Decoder** — For each receiver, the latent field is sampled at the
   receiver location (bilinear interpolation) and decoded through an MLP
   into a time-domain trace.

The Fourier layers use the standard spectral convolution from
Li et al. (2021) "Fourier Neural Operator for Parametric Partial
Differential Equations".

Training data is generated by running the existing FDTD solver with
randomised domain, source, and receiver configurations.
"""

from __future__ import annotations

import math

import torch
import torch.nn as nn
import torch.nn.functional as F


# -----------------------------------------------------------------------
# Spectral convolution (core FNO building block)
# -----------------------------------------------------------------------

class SpectralConv2d(nn.Module):
    """2-D Fourier-space convolution (complex multiply in frequency domain).

    Retains only the lowest ``modes1 × modes2`` Fourier modes.
    """

    def __init__(
        self,
        in_channels: int,
        out_channels: int,
        modes1: int,
        modes2: int,
    ) -> None:
        super().__init__()
        self.in_channels = in_channels
        self.out_channels = out_channels
        self.modes1 = modes1
        self.modes2 = modes2

        scale = 1.0 / (in_channels * out_channels)
        self.weights1 = nn.Parameter(
            scale * torch.randn(in_channels, out_channels, modes1, modes2, 2)
        )
        self.weights2 = nn.Parameter(
            scale * torch.randn(in_channels, out_channels, modes1, modes2, 2)
        )

    def _complex_mul(
        self, a: torch.Tensor, b: torch.Tensor
    ) -> torch.Tensor:
        """Batched complex multiplication using real-valued tensors.

        a: (batch, in_ch, x, y, 2)
        b: (in_ch, out_ch, x, y, 2)
        returns: (batch, out_ch, x, y, 2)
        """
        return torch.stack([
            torch.einsum("bixy,ioxy->boxy", a[..., 0], b[..., 0])
            - torch.einsum("bixy,ioxy->boxy", a[..., 1], b[..., 1]),
            torch.einsum("bixy,ioxy->boxy", a[..., 0], b[..., 1])
            + torch.einsum("bixy,ioxy->boxy", a[..., 1], b[..., 0]),
        ], dim=-1)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        batch_size = x.shape[0]
        # x: (batch, channels, ny, nx)

        # FFT along spatial dims.
        x_ft = torch.fft.rfft2(x)
        # x_ft: (batch, channels, ny, nx//2+1) complex

        # Convert to real-valued (batch, ch, ny, nx_half, 2).
        x_ft_real = torch.stack([x_ft.real, x_ft.imag], dim=-1)

        ny = x.shape[2]
        out_ft = torch.zeros(
            batch_size, self.out_channels, ny,
            x.shape[3] // 2 + 1, 2,
            device=x.device, dtype=x.dtype,
        )

        # Low-frequency modes (positive half).
        out_ft[:, :, :self.modes1, :self.modes2, :] = self._complex_mul(
            x_ft_real[:, :, :self.modes1, :self.modes2, :],
            self.weights1,
        )
        # Negative-frequency modes (wrapped at end of axis).
        out_ft[:, :, -self.modes1:, :self.modes2, :] = self._complex_mul(
            x_ft_real[:, :, -self.modes1:, :self.modes2, :],
            self.weights2,
        )

        # Back to complex and inverse FFT.
        out_complex = torch.complex(out_ft[..., 0], out_ft[..., 1])
        return torch.fft.irfft2(out_complex, s=(x.shape[2], x.shape[3]))


# -----------------------------------------------------------------------
# FNO block (spectral conv + pointwise conv + residual)
# -----------------------------------------------------------------------

class FNOBlock2d(nn.Module):
    """One Fourier layer: spectral conv + 1x1 conv + residual + GELU."""

    def __init__(
        self,
        width: int,
        modes1: int,
        modes2: int,
    ) -> None:
        super().__init__()
        self.spectral = SpectralConv2d(width, width, modes1, modes2)
        self.pointwise = nn.Conv2d(width, width, kernel_size=1)
        self.norm = nn.InstanceNorm2d(width)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return F.gelu(self.norm(self.spectral(x) + self.pointwise(x))) + x


# -----------------------------------------------------------------------
# Trace decoder (latent features at receiver location → time series)
# -----------------------------------------------------------------------

class TraceDecoder(nn.Module):
    """MLP that maps a latent vector to a time-domain receiver trace.

    Input: (batch, n_recv, latent_dim)
    Output: (batch, n_recv, n_time_steps)
    """

    def __init__(self, latent_dim: int, n_time_steps: int, hidden: int = 256) -> None:
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(latent_dim, hidden),
            nn.GELU(),
            nn.Linear(hidden, hidden),
            nn.GELU(),
            nn.Linear(hidden, n_time_steps),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.net(x)


# -----------------------------------------------------------------------
# Full FNO surrogate model
# -----------------------------------------------------------------------

class AcousticFNO(nn.Module):
    """Fourier Neural Operator surrogate for FDTD acoustic simulation.

    Input channels (concatenated along channel dim):
        0: velocity field (ny, nx), normalised
        1: source x-position indicator (Gaussian blob)
        2: source y-position indicator (Gaussian blob)
        3: source frequency encoding (uniform fill, normalised)

    The model produces a latent spatial field, then samples at each
    receiver position via bilinear interpolation and decodes to traces.

    Parameters
    ----------
    modes1, modes2 : int
        Number of Fourier modes retained in each spatial dimension.
    width : int
        Channel width of the FNO layers.
    n_layers : int
        Number of Fourier layers.
    n_time_steps : int
        Length of the output trace per receiver.
    in_channels : int
        Number of input channels (velocity + source encoding).
    """

    def __init__(
        self,
        modes1: int = 16,
        modes2: int = 16,
        width: int = 64,
        n_layers: int = 4,
        n_time_steps: int = 1000,
        in_channels: int = 4,
    ) -> None:
        super().__init__()
        self.n_time_steps = n_time_steps
        self.width = width

        # Lift input channels to FNO width.
        self.lift = nn.Conv2d(in_channels, width, kernel_size=1)

        # Fourier layers.
        self.layers = nn.ModuleList([
            FNOBlock2d(width, modes1, modes2)
            for _ in range(n_layers)
        ])

        # Projection to latent feature dimension.
        self.proj = nn.Conv2d(width, width, kernel_size=1)

        # Trace decoder.
        self.decoder = TraceDecoder(width, n_time_steps)

    def forward(
        self,
        field: torch.Tensor,
        receiver_positions: torch.Tensor,
        grid_x: torch.Tensor,
        grid_y: torch.Tensor,
    ) -> torch.Tensor:
        """Forward pass.

        Parameters
        ----------
        field : (batch, in_channels, ny, nx)
            Input field (velocity model + source encoding).
        receiver_positions : (batch, n_recv, 2)
            Receiver (x, y) positions in physical coordinates.
        grid_x : (batch,) or (nx,)
            Physical x-coordinates of grid columns.
        grid_y : (batch,) or (ny,)
            Physical y-coordinates of grid rows.

        Returns
        -------
        traces : (batch, n_recv, n_time_steps)
        """
        # Encoder: lift + Fourier layers.
        h = self.lift(field)
        for layer in self.layers:
            h = layer(h)
        h = self.proj(h)  # (batch, width, ny, nx)

        # Sample latent features at receiver positions via grid_sample.
        traces = self._sample_and_decode(
            h, receiver_positions, grid_x, grid_y
        )
        return traces

    def _sample_and_decode(
        self,
        latent: torch.Tensor,
        receiver_positions: torch.Tensor,
        grid_x: torch.Tensor,
        grid_y: torch.Tensor,
    ) -> torch.Tensor:
        """Bilinear sample latent field at receiver positions → decode.

        Parameters
        ----------
        latent : (batch, width, ny, nx)
        receiver_positions : (batch, n_recv, 2) — physical (x, y)
        grid_x, grid_y : 1-D tensors of physical coordinates

        Returns
        -------
        (batch, n_recv, n_time_steps)
        """
        batch, width, ny, nx = latent.shape
        n_recv = receiver_positions.shape[1]

        # Normalise receiver positions to [-1, 1] for grid_sample.
        x_min, x_max = grid_x[0], grid_x[-1]
        y_min, y_max = grid_y[0], grid_y[-1]

        # receiver_positions[..., 0] = x, [..1] = y
        rx_norm = 2.0 * (receiver_positions[..., 0] - x_min) / (x_max - x_min) - 1.0
        ry_norm = 2.0 * (receiver_positions[..., 1] - y_min) / (y_max - y_min) - 1.0

        # grid_sample expects (batch, n_points, 1, 2) with (x_norm, y_norm).
        grid = torch.stack([rx_norm, ry_norm], dim=-1)  # (batch, n_recv, 2)
        grid = grid.unsqueeze(2)  # (batch, n_recv, 1, 2)

        sampled = F.grid_sample(
            latent, grid, mode="bilinear", align_corners=True,
        )  # (batch, width, n_recv, 1)
        sampled = sampled.squeeze(-1).permute(0, 2, 1)  # (batch, n_recv, width)

        return self.decoder(sampled)


# -----------------------------------------------------------------------
# Input encoding helpers
# -----------------------------------------------------------------------

def encode_source_on_grid(
    grid_x: torch.Tensor,
    grid_y: torch.Tensor,
    source_x: float,
    source_y: float,
    sigma: float = 2.0,
) -> tuple[torch.Tensor, torch.Tensor]:
    """Create Gaussian blob channels for source position.

    Returns two (ny, nx) tensors: x-indicator and y-indicator.
    """
    yy = grid_y.unsqueeze(1)  # (ny, 1)
    xx = grid_x.unsqueeze(0)  # (1, nx)
    blob_x = torch.exp(-0.5 * ((xx - source_x) / sigma) ** 2)
    blob_y = torch.exp(-0.5 * ((yy - source_y) / sigma) ** 2)
    return blob_x.expand_as(yy * xx), blob_y.expand_as(yy * xx)


def prepare_fno_input(
    velocity_field: torch.Tensor,
    grid_x: torch.Tensor,
    grid_y: torch.Tensor,
    source_x: float,
    source_y: float,
    source_freq: float,
    freq_scale: float = 500.0,
    sigma: float = 2.0,
) -> torch.Tensor:
    """Build the 4-channel FNO input tensor.

    Parameters
    ----------
    velocity_field : (ny, nx) — sound speed in m/s.
    grid_x : (nx,) — x coordinates.
    grid_y : (ny,) — y coordinates.
    source_x, source_y : source position.
    source_freq : dominant source frequency [Hz].
    freq_scale : normalisation for frequency channel.
    sigma : Gaussian blob width for source position [m].

    Returns
    -------
    (4, ny, nx) tensor ready for batching.
    """
    ny, nx = velocity_field.shape

    # Channel 0: normalised velocity.
    c_min, c_max = velocity_field.min(), velocity_field.max()
    if c_max - c_min > 1e-6:
        vel_norm = (velocity_field - c_min) / (c_max - c_min)
    else:
        vel_norm = torch.zeros_like(velocity_field)

    # Channels 1-2: source position blobs.
    src_x_blob, src_y_blob = encode_source_on_grid(
        grid_x, grid_y, source_x, source_y, sigma=sigma,
    )

    # Channel 3: frequency encoding.
    freq_ch = torch.full((ny, nx), source_freq / freq_scale,
                         dtype=velocity_field.dtype)

    return torch.stack([vel_norm, src_x_blob, src_y_blob, freq_ch], dim=0)
