"""FNO surrogate model training and evaluation.

Loads .npz samples generated by ``fno_data_gen.py``, trains the
:class:`~acoustic_sim.ml.fno.AcousticFNO` model, and saves checkpoints.

Usage
-----
    python -m acoustic_sim.ml.fno_training \\
        --data-dir data/fno_train --epochs 200 --batch-size 8

    python -m acoustic_sim.ml.fno_training \\
        --data-dir data/fno_train --checkpoint model.pt --evaluate-only
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, Dataset

from acoustic_sim.ml.fno import AcousticFNO, prepare_fno_input


# -----------------------------------------------------------------------
# Dataset
# -----------------------------------------------------------------------

class FNODataset(Dataset):
    """Lazy-loading dataset of FDTD simulation samples.

    Each sample is an .npz file containing velocity_field, grid_x,
    grid_y, receiver_positions, traces, source_x, source_y, source_freq.

    Because samples may have different numbers of receivers and time
    steps, __getitem__ pads to a fixed size determined by scanning the
    manifest.
    """

    def __init__(
        self,
        data_dir: str | Path,
        max_receivers: int = 24,
        max_time_steps: int = 0,
    ) -> None:
        self.data_dir = Path(data_dir)
        self.files = sorted(self.data_dir.glob("sample_*.npz"))
        if not self.files:
            raise FileNotFoundError(
                f"No sample_*.npz files in {self.data_dir}"
            )
        self.max_receivers = max_receivers

        # Determine max time steps from first sample if not specified.
        if max_time_steps <= 0:
            with np.load(str(self.files[0])) as d:
                self.max_time_steps = d["traces"].shape[1]
        else:
            self.max_time_steps = max_time_steps

    def __len__(self) -> int:
        return len(self.files)

    def __getitem__(self, idx: int) -> dict[str, torch.Tensor]:
        data = np.load(str(self.files[idx]))

        vel = data["velocity_field"]  # (ny, nx)
        grid_x = data["grid_x"]      # (nx,)
        grid_y = data["grid_y"]      # (ny,)
        recv = data["receiver_positions"]  # (n_recv, 2) or (n_recv, 3)
        traces = data["traces"]       # (n_recv, n_steps)
        src_x = float(data["source_x"])
        src_y = float(data["source_y"])
        src_freq = float(data["source_freq"])

        # Use only x, y for receiver positions (2D FNO).
        recv_xy = recv[:, :2]

        # Build FNO input.
        field = prepare_fno_input(
            torch.tensor(vel, dtype=torch.float32),
            torch.tensor(grid_x, dtype=torch.float32),
            torch.tensor(grid_y, dtype=torch.float32),
            src_x, src_y, src_freq,
        )  # (4, ny, nx)

        # Pad receivers and traces to fixed size.
        n_recv = recv_xy.shape[0]
        n_steps = traces.shape[1]
        n_recv_pad = self.max_receivers
        n_steps_pad = self.max_time_steps

        recv_padded = np.zeros((n_recv_pad, 2), dtype=np.float32)
        recv_padded[:n_recv] = recv_xy[:n_recv_pad]

        traces_padded = np.zeros((n_recv_pad, n_steps_pad), dtype=np.float32)
        nr = min(n_recv, n_recv_pad)
        ns = min(n_steps, n_steps_pad)
        traces_padded[:nr, :ns] = traces[:nr, :ns]

        # Mask for valid receivers.
        recv_mask = np.zeros(n_recv_pad, dtype=np.float32)
        recv_mask[:nr] = 1.0

        return {
            "field": field,
            "receiver_positions": torch.tensor(recv_padded),
            "traces": torch.tensor(traces_padded),
            "recv_mask": torch.tensor(recv_mask),
            "grid_x": torch.tensor(grid_x),
            "grid_y": torch.tensor(grid_y),
            "n_receivers": torch.tensor(nr, dtype=torch.long),
        }


# -----------------------------------------------------------------------
# Training
# -----------------------------------------------------------------------

def train_fno(
    model: AcousticFNO,
    train_loader: DataLoader,
    val_loader: DataLoader | None = None,
    n_epochs: int = 100,
    lr: float = 1e-3,
    weight_decay: float = 1e-5,
    checkpoint_dir: str | Path = "checkpoints",
    verbose: bool = True,
) -> dict:
    """Train the FNO model.

    Uses relative L2 loss (trace-level) masked to valid receivers.
    """
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = model.to(device)
    optimizer = torch.optim.AdamW(
        model.parameters(), lr=lr, weight_decay=weight_decay,
    )
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer, T_max=n_epochs, eta_min=lr / 100,
    )

    ckpt_dir = Path(checkpoint_dir)
    ckpt_dir.mkdir(parents=True, exist_ok=True)

    history = {"train_loss": [], "val_loss": []}

    for epoch in range(n_epochs):
        model.train()
        epoch_loss = 0.0
        n_batches = 0

        for batch in train_loader:
            field = batch["field"].to(device)
            recv = batch["receiver_positions"].to(device)
            target = batch["traces"].to(device)
            mask = batch["recv_mask"].to(device)
            grid_x = batch["grid_x"][0].to(device)
            grid_y = batch["grid_y"][0].to(device)

            pred = model(field, recv, grid_x, grid_y)

            # Relative L2 loss, masked.
            diff = (pred - target) ** 2
            # Sum over time, mean over receivers.
            per_recv = diff.sum(dim=-1)  # (batch, n_recv)
            target_norm = (target ** 2).sum(dim=-1).clamp(min=1e-10)
            rel_err = (per_recv / target_norm) * mask.unsqueeze(0) if mask.ndim == 1 else (per_recv / target_norm) * mask

            # Mean over valid receivers.
            n_valid = mask.sum(dim=-1).clamp(min=1.0)
            loss = (rel_err.sum(dim=-1) / n_valid).mean()

            optimizer.zero_grad()
            loss.backward()
            nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
            optimizer.step()

            epoch_loss += loss.item()
            n_batches += 1

        scheduler.step()
        avg_loss = epoch_loss / max(n_batches, 1)
        history["train_loss"].append(avg_loss)

        # Validation.
        val_loss = float("nan")
        if val_loader is not None:
            val_loss = _evaluate(model, val_loader, device)
        history["val_loss"].append(val_loss)

        if verbose and (epoch + 1) % 10 == 0:
            lr_now = scheduler.get_last_lr()[0]
            print(
                f"  Epoch {epoch + 1:4d}/{n_epochs}: "
                f"train={avg_loss:.6f}  val={val_loss:.6f}  "
                f"lr={lr_now:.2e}"
            )

        # Checkpoint every 50 epochs.
        if (epoch + 1) % 50 == 0:
            torch.save(
                model.state_dict(),
                str(ckpt_dir / f"fno_epoch_{epoch + 1:04d}.pt"),
            )

    # Final checkpoint.
    torch.save(model.state_dict(), str(ckpt_dir / "fno_final.pt"))
    return history


def _evaluate(
    model: AcousticFNO,
    loader: DataLoader,
    device: torch.device,
) -> float:
    """Compute mean relative L2 loss on a dataset."""
    model.eval()
    total_loss = 0.0
    n_batches = 0

    with torch.no_grad():
        for batch in loader:
            field = batch["field"].to(device)
            recv = batch["receiver_positions"].to(device)
            target = batch["traces"].to(device)
            mask = batch["recv_mask"].to(device)
            grid_x = batch["grid_x"][0].to(device)
            grid_y = batch["grid_y"][0].to(device)

            pred = model(field, recv, grid_x, grid_y)

            diff = (pred - target) ** 2
            per_recv = diff.sum(dim=-1)
            target_norm = (target ** 2).sum(dim=-1).clamp(min=1e-10)
            rel_err = (per_recv / target_norm) * mask

            n_valid = mask.sum(dim=-1).clamp(min=1.0)
            loss = (rel_err.sum(dim=-1) / n_valid).mean()

            total_loss += loss.item()
            n_batches += 1

    return total_loss / max(n_batches, 1)


# -----------------------------------------------------------------------
# CLI
# -----------------------------------------------------------------------

def main() -> None:
    p = argparse.ArgumentParser(
        description="Train FNO acoustic surrogate model",
    )
    p.add_argument("--data-dir", required=True,
                   help="Directory of .npz training samples")
    p.add_argument("--val-split", type=float, default=0.1,
                   help="Fraction of samples for validation")
    p.add_argument("--epochs", type=int, default=200)
    p.add_argument("--batch-size", type=int, default=8)
    p.add_argument("--lr", type=float, default=1e-3)
    p.add_argument("--modes", type=int, default=16,
                   help="FNO Fourier modes per dimension")
    p.add_argument("--width", type=int, default=64,
                   help="FNO channel width")
    p.add_argument("--n-layers", type=int, default=4)
    p.add_argument("--checkpoint-dir", default="checkpoints/fno")
    p.add_argument("--checkpoint", default=None,
                   help="Load from checkpoint (for resume or evaluate)")
    p.add_argument("--evaluate-only", action="store_true")
    p.add_argument("--max-receivers", type=int, default=24)
    args = p.parse_args()

    # Load dataset.
    dataset = FNODataset(
        args.data_dir,
        max_receivers=args.max_receivers,
    )
    n_val = max(1, int(len(dataset) * args.val_split))
    n_train = len(dataset) - n_val
    train_ds, val_ds = torch.utils.data.random_split(
        dataset, [n_train, n_val],
        generator=torch.Generator().manual_seed(42),
    )
    train_loader = DataLoader(
        train_ds, batch_size=args.batch_size, shuffle=True, num_workers=0,
    )
    val_loader = DataLoader(
        val_ds, batch_size=args.batch_size, shuffle=False, num_workers=0,
    )

    print(f"Dataset: {len(dataset)} samples "
          f"({n_train} train, {n_val} val)")
    print(f"Max time steps: {dataset.max_time_steps}")
    print(f"Max receivers: {dataset.max_receivers}")

    # Build model.
    model = AcousticFNO(
        modes1=args.modes,
        modes2=args.modes,
        width=args.width,
        n_layers=args.n_layers,
        n_time_steps=dataset.max_time_steps,
    )

    total_params = sum(p.numel() for p in model.parameters())
    print(f"Model: {total_params:,} parameters")

    if args.checkpoint:
        model.load_state_dict(
            torch.load(args.checkpoint, map_location="cpu", weights_only=True)
        )
        print(f"Loaded checkpoint: {args.checkpoint}")

    if args.evaluate_only:
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        model = model.to(device)
        full_loader = DataLoader(
            dataset, batch_size=args.batch_size, shuffle=False,
        )
        loss = _evaluate(model, full_loader, device)
        print(f"Evaluation loss (relative L2): {loss:.6f}")
        return

    history = train_fno(
        model, train_loader, val_loader,
        n_epochs=args.epochs,
        lr=args.lr,
        checkpoint_dir=args.checkpoint_dir,
    )

    # Save history.
    hist_path = Path(args.checkpoint_dir) / "history.json"
    with open(str(hist_path), "w") as f:
        json.dump(history, f, indent=2)
    print(f"Saved training history to {hist_path}")


if __name__ == "__main__":
    main()
